---
name: WAU - Create New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        default: "Patch"
        description: Select next release type
        options:
          - Patch
          - Minor
          - Major
        required: true
      pre-release:
        type: boolean
        description: Set as Pre-release version

permissions:
  contents: write

jobs:
  build:
    name: Create Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.10
        id: versioning
        with:
          releaseType: ${{ github.event.inputs.version }}
          incrementPerCommit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Overwrite Version.txt file
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: Winget-AutoUpdate/Version.txt
          write-mode: overwrite
          contents: "${{ steps.versioning.outputs.version }}"

      - name: Commit & Push
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Changed version to ${{ steps.versioning.outputs.version }}"

      - name: Build project
        run: |
          # Get MDT from Microsoft
          wget https://download.microsoft.com/download/3/3/9/339BE62D-B4B8-4956-B58D-73C4685FC492/MicrosoftDeploymentToolkit_x64.msi
          # Extract MSI
          7z x MicrosoftDeploymentToolkit_x64.msi
          # Copy ServiceUI.exe to Winget-AutoUpdate folder
          mv Modena_File206 Winget-AutoUpdate/ServiceUI.exe
          # Zip WAU
          zip -r WAU.zip Winget-AutoUpdate
          zip WAU.zip Winget-AutoUpdate-Install.ps1
          zip WAU.zip excluded_apps.txt
          zip WAU.zip install.bat
          zip WAU.zip uninstall.bat
          # Zip ADMX
          cd Policies
          zip -r ../WAU_ADMX.zip *
          cd ..

      - name: Create release
        uses: "ncipollo/release-action@v1"
        with:
          tag: "v${{ steps.versioning.outputs.version }}"
          prerelease: ${{ github.event.inputs.pre-release }}
          generateReleaseNotes: true
          name: "v${{ steps.versioning.outputs.version }}"
          artifacts: "WAU.zip,WAU_ADMX.zip"
